services:
  llamacpp-wasm-builder:
    container_name: llamacpp-wasm-builder
    build:
      context: .
      dockerfile_inline: |
        ARG EMSDK_IMAGE_TAG=none  # modify it in build_wasm.sh
        FROM emscripten/emsdk:$${EMSDK_IMAGE_TAG}
        RUN apt update && apt install -y git
      args:
        EMSDK_IMAGE_TAG: ${EMSDK_IMAGE_TAG}
    user: "${D_UID}:${D_GID}"
    volumes:
      - ..:/source:Z
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -e
        cd /source

        DAWN_TAG=v20251027.212519
        EMDAWN_PKG="emdawnwebgpu_pkg-$${DAWN_TAG}.zip"
        EMDAWNWEBGPU_DIR="/source/emdawnwebgpu_pkg"
        echo "Downloading $${EMDAWN_PKG}"
        curl -L -o emdawn.zip \
          "https://github.com/google/dawn/releases/download/$${DAWN_TAG}/$${EMDAWN_PKG}"
        python3 -c "import zipfile; zf=zipfile.ZipFile('emdawn.zip','r'); zf.extractall('/source'); zf.close()"
        python3 /source/scripts/patch_dawn_adapter_info.py

        COMMON_EMCC_FLAGS="--no-entry -O3 -msimd128 -DNDEBUG -flto=full -frtti -sEXPORT_ES6=0 -sMODULARIZE=0 -sINITIAL_MEMORY=128MB -sMAXIMUM_MEMORY=4096MB -sALLOW_MEMORY_GROWTH=1 -sFORCE_FILESYSTEM=1 -sEXPORTED_FUNCTIONS=_main,_wllama_malloc,_wllama_start,_wllama_action,_wllama_exit,_wllama_debug -sEXPORTED_RUNTIME_METHODS=ccall,cwrap,HEAPU8,MEMFS,FS,mmapAlloc -sNO_EXIT_RUNTIME=1 -Wno-unused-command-line-argument -sIMPORTED_MEMORY"

        build_target() {
          local build_name="$1"
          local build_dir="$2"
          local cmake_flag="$3"
          local extra_flags="$4"
          local emcc_flags="$${COMMON_EMCC_FLAGS} $${extra_flags}"
          local output_dir="src/$${build_dir#wasm/}"

          echo "Building $${build_name}"
          mkdir -p "$${build_dir}"
          cd "$${build_dir}"
          export EMCC_CFLAGS=""
          emcmake cmake ../.. "$${cmake_flag}" -DEMDAWNWEBGPU_DIR="$${EMDAWNWEBGPU_DIR}"
          export EMCC_CFLAGS="$${emcc_flags}"
          emmake make wllama -j
          cd /source

          echo "$${build_dir}"; ls -lh "$${build_dir}"
          mkdir -p "$${output_dir}"
          cp "$${build_dir}/wllama.js" "$${output_dir}"
          cp "$${build_dir}/wllama.wasm" "$${output_dir}"
        }

        # build_target "JSPI single-thread" "wasm/jspi-single-thread" "-DGGML_WEBGPU_JSPI=ON" "-fwasm-exceptions -sJSPI -sJSPI_EXPORTS=['wllama_start','wllama_action']"

        # build_target "JSPI multi-thread" "wasm/jspi-multi-thread" "-DGGML_WEBGPU_JSPI=ON" "-fwasm-exceptions -sJSPI -sJSPI_EXPORTS=['wllama_start','wllama_action'] -pthread -sUSE_PTHREADS=1 -sPTHREAD_POOL_SIZE=Module[\\\"pthreadPoolSize\\\"]"

        build_target "ASYNCIFY single-thread" "wasm/asyncify-single-thread" "-DGGML_WEBGPU_JSPI=OFF" "-fexceptions -sASYNCIFY=1"

        # build_target "ASYNCIFY multi-thread" "wasm/asyncify-multi-thread" "-DGGML_WEBGPU_JSPI=OFF" "-fexceptions -sASYNCIFY=1 -pthread -sUSE_PTHREADS=1 -sPTHREAD_POOL_SIZE=Module[\\\"pthreadPoolSize\\\"]"
