// This file is generated by scripts/generate_wasm_from_cdn.js
// Do not edit this file directly

const WasmFromCDN = {
  'jspi/single-thread/wllama.wasm':
    'https://cdn.jsdelivr.net/npm/@reeselevine/wllama@3.0.0/src/jspi-single-thread/wllama.wasm',
  'jspi/multi-thread/wllama.wasm':
    'https://cdn.jsdelivr.net/npm/@reeselevine/wllama@3.0.0/src/jspi-multi-thread/wllama.wasm',
  'asyncify/single-thread/wllama.wasm':
    'https://cdn.jsdelivr.net/npm/@reeselevine/wllama@3.0.0/src/asyncify-single-thread/wllama.wasm',
  'asyncify/multi-thread/wllama.wasm':
    'https://cdn.jsdelivr.net/npm/@reeselevine/wllama@3.0.0/src/asyncify-multi-thread/wllama.wasm',
};

export default WasmFromCDN;